config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  root 'posts#index'
  resources :posts, except: %i[index edit update] do
    scope module: :posts do
      resources :comments, only: %i[create destroy]
      resources :likes, only: %i[create destroy]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :category

  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :title, :body, presence: true
  validates :title, length: { minimum: 5 }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_ancestry

  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

class Posts::ApplicationController < ApplicationController
  before_action :authenticate_user!
  before_action :resource_post

  def resource_post
    @resource_post ||= Post.find(params[:post_id])
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < Posts::ApplicationController
  def create
    comment = @resource_post.comments.build(comments_params)
    comment.user = current_user

    if comment.save
      redirect_to post_path(@resource_post), notice: t('.create.success')
    else
      redirect_to post_path(@resource_post)
    end
  end

  def destroy
    PostComment.find(params[:id]).destroy!
    redirect_to post_path(@resource_post), status: :see_other, notice: t('.destroy.success')
  end

  private

  def comments_params
    params.require(:post_comment).permit(:content, :parent_id)
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

class Posts::LikesController < Posts::ApplicationController
  def create
    like = @resource_post.likes.new
    like.user = current_user
    like.save
    redirect_to @resource_post
  end

  def destroy
    like = PostLike.find(params[:id])

    if like.user == current_user
      like.destroy!
    end
    redirect_to @resource_post
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show destroy]

  def index
    @posts = Post.includes(:creator)
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: t('.create.success') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: t('.destroy.success') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/comments/_form.html.slim
= simple_form_for(post_comment, url: local_assigns[:url]) do |f|
  = render 'shared/errors', form: f

  .form-inputs
    = f.input :content
    - if post_comment.parent
      = f.hidden_field :parent_id, value: post_comment.parent.id

  .form-actions
    = f.button :submit, t("helpers.submit.comment.create")

app/views/comments/_post_comment.html.slim
- data = { bs_target: "#response_comment-#{comment.id}", bs_toggle: 'collapse' }
.col-md-12
  .card.mb-3
    .card-header.d-flex.justify-content-between
      .span.me-2 = comment.user.email
      .span.me-2 = comment.created_at.to_fs(:long)
    .card-body
      .card-text.mb-2
        = comment.content

      = render 'comments/comments', comments: comment.children

      .card-footer.border-0
        = link_to t('.reply'), '#',
          class: 'fs-6 text-decoration-underline text-lowercase collapsed',
          type: 'button',
          'aria-expanded' => false,
          'aria-controls' => "response_comment-#{comment.id}",
          data: data

        .ms-2.collapse id="response_comment-#{comment.id}"
          = render 'comments/form',
            post_comment: comment.children.build,
            url: post_comments_path(comment.post)

app/views/layouts/_header.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        p.navbar-brand = t('layouts.header.title')
    .navbar.navbar-expand-md.navbar-light.me-auto
    ul.nav.nav-pills
      - if user_signed_in?
        li.nav-item.me-2
          p.nav-link.disabled
            = current_user.email
        li.nav-item.me-2
          = link_to t('.new_post'),
            new_post_path,
            class: 'nav-link link-dark'
        li.nav-item.me-2
          = link_to t('.sign_out'),
            destroy_user_session_path,
            class: 'nav-link link-dark',
            data: { turbo_method: 'delete' }
      - else
        li.nav-item.me-2
          = link_to t('.sign_in'),
            new_user_session_path,
            class: 'nav-link link-dark'
        li.nav-item.me-2
          = link_to t('.sign_up'),
            new_user_registration_path,
            class: 'nav-link link-dark'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || t('layouts.header.title')
    meta[name='viewport' content='width=device-width,initial-scale=1']
    meta[name='apple-mobile-web-app-capable' content='yes']
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    link[rel='manifest' href='/manifest.json']
    link[rel='icon' href='/icon.png' type='image/png']
    link[rel='icon' href='/icon.svg' type='image/svg+xml']
    link[rel='apple-touch-icon' href='/icon.png']
    = stylesheet_link_tag 'application',
                          'data-turbo-track': 'reload'
    = javascript_include_tag 'application',
                             'data-turbo-track': 'reload',
                             type: 'module'
  body.d-flex.flex-column.h-100
    = render 'layouts/header'
    .container.my-4
      - if notice.present?
        p.notice style='color: green' = notice
      - if alert.present?
        p.alert = alert
      = yield

app/views/pages/home.html.slim
main.flex-shrink-0
  .container
    h1.mt-5
      = t('pages.home.title')
    = render 'posts/posts', posts: @posts

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = render 'shared/errors', form: f

  .form-inputs
    = f.input :title
    = f.input :body
    = f.input :category_id,
      collection: Category.all,
      label_method: :name,
      value_method: :id

  .form-actions
    = f.button :submit

app/views/posts/_post.html.slim
.col-md-12
  .card.mb-3
    .card-body
      h2.h5.card-title
        = link_to post_path(post), class: 'link-dark text-decoration-none' do
          = post.title

      .card-text.mb-2
        = truncate(post.body, length: 300)
      .d-flex
        .text-right.small.text-muted.mt-auto
          .span.me-2 = post.creator.email
        .text-right.small.text-muted.mt-auto
          .span.me-2 = time_ago_in_words(post.created_at)

app/views/posts/_posts.html.slim
.row
  - posts.each do |post|
    == render post

app/views/posts/comments/_comments.html.slim
.row
  - comments.each do |comment|
    == render 'posts/comments/post_comment', comment:

app/views/posts/comments/_form.html.slim
= simple_form_for(post_comment, url: local_assigns[:url]) do |f|
  = render 'shared/errors', form: f

  .form-inputs
    = f.input :content, label: false
    - if post_comment.parent
      = f.hidden_field :parent_id, value: post_comment.parent.id

  .form-actions
    = f.button :submit, t('helpers.submit.comment.create')

app/views/posts/comments/_post_comment.html.slim
- data = { bs_target: "#response_comment-#{comment.id}", bs_toggle: 'collapse' }
.col-md-12
  .card.mb-3
    .card-header.d-flex.justify-content-between
      .span.me-2 = comment.user.email
      .span.me-2 = l(comment.created_at, format: :long)
    .card-body
      .card-text.mb-2
        = comment.content

      = render 'posts/comments/comments', comments: comment.children

      .card-footer.border-0
        = link_to t('.reply'), '#',
          class: 'fs-6 text-decoration-underline text-lowercase collapsed',
          type: 'button',
          'aria-expanded' => false,
          'aria-controls' => "response_comment-#{comment.id}",
          data: data

        .ms-2.collapse id="response_comment-#{comment.id}"
          = render 'posts/comments/form',
            post_comment: comment.children.build,
            url: post_comments_path(comment.post)

app/views/posts/index.html.slim
main.flex-shrink-0
  .container
    h1.mt-5
      = t('layouts.header.title')
    = render 'posts/posts', posts: @posts

app/views/posts/new.html.slim
h1 = t('.title')

== render 'form', post: @post

app/views/posts/show.html.slim
.col-12
  h1.mb-4.mb-lg-5
    = @post.title
  p
    = @post.body

  .d-flex
    span.me-2 = @post.creator.email
    span.me-2 = time_ago_in_words(@post.created_at)
    span.me-2
      - if @post.liked_users.include?(current_user)
        - like = current_user.likes.find_by(post_id: @post.id)
        = link_to post_like_path(@post, like),
          data: { turbo_method: 'delete' } do
          span.me-2 = @post.likes.count
          i.bi.bi-hand-thumbs-up-fill
      - else
        = link_to post_likes_path(@post),
          data: { turbo_method: 'post' } do
          span.me-2 = @post.likes.count
          i.bi.bi-hand-thumbs-up

.mt-3
  span.lead = t('.comments')
  = render 'posts/comments/form',
    post_comment: PostComment.new,
    url: post_comments_path(@post)

  = render 'posts/comments/comments',
    comments: @post.comments.includes(:user).roots

app/views/shared/_errors.html.slim
= form.error_notification
  = form.error_notification message: form.object.errors[:base].to_sentence \
    if form.object.errors[:base].present?